# remark: see https://stackoverflow.com/questions/37715224/copy-multiple-directories-with-one-command
FROM node:16-slim

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

# ENV REACT_APP_BACKEND_URL=http://localhost:8080
ENV REACT_APP_BACKEND_URL=http://localhost/api

RUN npm run build

RUN npm install -g serve

RUN useradd -m frontuser
USER frontuser

CMD ["serve", "-s", "-l", "5000", "build"]
