version: '3.8'

services:
  frontend:
    build:
      context: ./example-frontend
    ports:
      - "5000:5000"

  backend:
    build:
      context: ./example-backend
    ports:
      - "8080:8080"
    environment:
      REDIS_HOST: redis

  redis:
    image: redis:7.2-rc-alpine
