FROM golang:1.16-alpine

WORKDIR /usr/src/app

COPY go.mod go.sum ./

RUN go mod download && go mod verify

COPY . .

ENV REQUEST_ORIGIN=http://localhost:5000

EXPOSE 8080

RUN go build

CMD ["./server"]
